### ISSUE TITLE
Policy not fully working

### ISSUE THREAD

**Issue by zietbukuel** [TappNetwork/filament-auditing#10]
PHP 8.1
Laravel 10

I've created a policy with audit() and restoreAudit():

```
public function audit(User $user, Site $site): bool
{
    return $user->can('view audits');
}

public function restoreAudit(User $user, Site $site): bool
{
    return $user->can('restore audits');
}
```

However, only audit() is working correctly. I'm not able to get restoreAudit() working because anyone can restore an audit. What am I missing here? Thanks.

**Comment by andreia** [comment]
@zietbukuel Thank you for reporting :)

Just released a fix for it: https://github.com/TappNetwork/filament-auditing/releases/tag/v1.8.1
Could you please check if it's okay now?
