### ISSUE TITLE
Filament v3 - Upgrade

### ISSUE THREAD

**Issue by martin-arvisais** [TappNetwork/filament-auditing#14]
I would like to complete my upgrade to Filament v3. Do you plan to make this wonderful package of yours compatible with Filament v3?

**Comment by andreia** [comment]
@martin-arvisais Thank you! Glad you're enjoying it!
I'm working on it, I'll publish it soon :)

**Comment by martin-arvisais** [comment]
Hi, i didn't get the chance to make it work. Here's my error when i'm opening a page having the relation 'AuditsRelationManager::class'
![image](https://github.com/TappNetwork/filament-auditing/assets/43321941/4f96a9ed-6291-443e-80dc-3b5fce74f10a)

Sorry for the late reply, i try many thing before reply on it

**Comment by jansgescheit** [comment]
Yeah got same issue as @martin-arvisais, any ideas?

**Comment by andreia** [comment]
@jansgescheit @martin-arvisais 
I wasn't able to reproduce this error. 
Could you please show me how I can reproduce it (steps to follow, or share a repository, or a snippet)?

What versions are the following commands displaying?

```bash
composer show tapp/filament-auditing
composer show filament/filament
```

**Comment by jansgescheit** [comment]
@andreia 

When I was just looking for the information you needed. I noticed in my shell history that I had run `php artisan filament:optimize` (For whatever reason). 
I then had a look at the cache under `src/bootstrap/cache/filament/panels/admin.php`. The Livewire component `tapp.filament-auditing.relation-managers.audits-relation-manager` is missing in the cache listing. 

The solution is not to execute `php artisan filament:optimize` locally or to repeat it after a `composer update|require`.
